version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgresHack
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: everhack
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  default:
    name: everhack