version: "3.9"
services:

  backend:
    image: ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
    container_name: orderopatorio-back-${CI_ENVIRONMENT_NAME}
    restart: always
    environment:
      JAVA_OPTS: ${JAVA_OPTS}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE} # set in .gitlab-ci.yml
      SPRING_DATASOURCE_URL: jdbc:postgresql://orderopatorio-postgres-${CI_ENVIRONMENT_NAME}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_TOKEN: ${TELEGRAM_BOT_TOKEN}
      APP_SHEET_ID: ${SHEET_ID}
      APP_WEB_APP_URL: ${WEB_APP_URL}
    ports:
      - ${PORT}:8080
      - ${ADDITIONAL_PORT}:8180
    networks:
      - orderopatorio

networks:
  orderopatorio:
    name: orderopatorio-${CI_ENVIRONMENT_NAME}
