spring:
  application:
    name: EverHack Back
  datasource:
    url: jdbc:postgresql://localhost:5432/everhack
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration

server:
  compression:
    enabled: true
  servlet:
    application-display-name: ${spring.application.name}
    context-path: /api/v1
  error:
    whitelabel:
      enabled: true
    include-stacktrace: on_param
