CREATE TABLE course_steps
(
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_id BIGINT,
  title     VARCHAR(255),
  CONSTRAINT pk_course_steps PRIMARY KEY (id)
);

CREATE TABLE curriculum_elements
(
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  curriculum_id BIGINT,
  type          VARCHAR(255),
  position      INTEGER                                 NOT NULL,
  status        VARCHAR(255),
  title         VARCHAR(255),
  CONSTRAINT pk_curriculum_elements PRIMARY KEY (id)
);

CREATE TABLE curriculums
(
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  role_id     BIGINT,
  name        VARCHAR(255),
  description VARCHAR(255),
  CONSTRAINT pk_curriculums PRIMARY KEY (id)
);

CREATE TABLE roles
(
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title     VARCHAR(255),
  parent_id BIGINT,
  current   BOOLEAN                                 NOT NULL,
  blocked   BOOLEAN                                 NOT NULL,
  CONSTRAINT pk_roles PRIMARY KEY (id)
);

ALTER TABLE course_steps
  ADD CONSTRAINT FK_COURSE_STEPS_ON_COURSE FOREIGN KEY (course_id) REFERENCES curriculum_elements (id);

ALTER TABLE curriculums
  ADD CONSTRAINT FK_CURRICULUMS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE curriculum_elements
  ADD CONSTRAINT FK_CURRICULUM_ELEMENTS_ON_CURRICULUM FOREIGN KEY (curriculum_id) REFERENCES curriculums (id);

ALTER TABLE roles
  ADD CONSTRAINT FK_ROLES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES roles (id);